/**
 * SURF CANONICAL MAP IDENTITY — the surf-world competitive board.
 *
 * A SURF board is stored under a NAMESPACED track id built from the OFFICIAL
 * SONG id + the SURF generation version + the ACTUAL shipped map fingerprint.
 * This guarantees a surf record can never be confused with, or merged into, a
 * NORMAL record on the same song, and an arbitrary uploaded song (which has no
 * official catalog id) can never create a world board at all.
 *
 * The name is deterministic and reproducible from the SAME inputs the client
 * uses:
 *
 *   official song id   (the trusted catalog id, never a filename)
 *   SURF_GENERATION_VERSION
 *   mapFingerprint     (content hash of the final assembled surf map)
 *   movementVersion / generatorVersion / analysisFingerprint
 *
 * `computeSurfMapIdentity` builds the identity from a regenerated surf track;
 * the registry below is the SHIPPED, precomputed canonical set the server and
 * the client both accept. It is regenerated by
 * `tests/CanonicalSurfMaps.test.ts` exactly like the normal registry.
 */

import { SURF_GENERATION_VERSION } from '../generation/CourseType';
import { MapIdentity, RegistryEntry, buildMapIdentityString, computeMapIdentity } from './MapIdentity';
import { GeneratedTrack } from '../generation/GenerationTypes';
import { TrackAnalysis } from '../audio/AudioFeatures';
import { PLAYHEAD_MOVEMENT_V1 } from '../player/MovementConfig';
import { murmurHash3, seedToHex } from '../utils/hash';
import { computeAnalysisIdentity } from './MapIdentity';

/** Namespace prefix for a surf board track id. */
export const SURF_BOARD_NAMESPACE = 'surf';

/**
 * Deterministic namespaced board id for an official SURF map. The fingerprint
 * is part of the id so ANY geometry/version change automatically opens a fresh
 * board instead of silently mixing times from an older course.
 */
export function surfBoardTrackId(officialTrackId: string, mapFingerprint: string): string {
  return `${SURF_BOARD_NAMESPACE}:${officialTrackId}:v${SURF_GENERATION_VERSION}:${mapFingerprint}`;
}

/** Generator version string for a SURF map (kept identical to computeMapIdentity). */
export function surfGeneratorVersion(): string {
  return `surf_gen_${SURF_GENERATION_VERSION}`;
}

/**
 * Movement identity, duplicated from MapIdentity's derivation so a surf board
 * id can be verified without importing the whole module graph twice.
 */
export const SURF_MOVEMENT_VERSION: string = (() => {
  const c = PLAYHEAD_MOVEMENT_V1;
  const canonical = [
    `g${c.gravity}`, `j${c.jumpVelocity}`, `ga${c.groundAcceleration}`,
    `aa${c.airAcceleration}`, `gw${c.maxGroundWishSpeed}`, `aw${c.maxAirWishSpeed}`,
    `ss${c.supplementalAirSteer}`, `f${c.friction}`, `st${c.stopSpeed}`,
    `cy${c.coyoteTime}`, `jb${c.jumpBufferTime}`, `ph${c.playerHeight}`,
    `pr${c.playerRadius}`, `eh${c.eyeHeight}`, `su${c.speedUnitScale}`
  ].join('|');
  return `phmv1_${seedToHex(murmurHash3(canonical, 0x504c4d56))}`;
})();

export function surfMovementVersion(): string {
  return SURF_MOVEMENT_VERSION;
}

/**
 * Full SURF identity for a regenerated official surf track. `trackId` is the
 * NAMESPACED board id, so the returned identity verifies against the SURF
 * registry and never against the NORMAL one.
 */
export function computeSurfMapIdentity(
  officialTrackId: string,
  track: GeneratedTrack,
  analysis: TrackAnalysis
): MapIdentity {
  const base = computeMapIdentity(officialTrackId, track, analysis);
  return {
    ...base,
    trackId: surfBoardTrackId(officialTrackId, base.mapFingerprint),
    mapVersion: SURF_GENERATION_VERSION,
    generatorVersion: surfGeneratorVersion()
  };
}

import { OFFICIAL_SURF_MAP_REGISTRY } from './OfficialSurfMapRegistry';

/** Canonical SURF registry entries (namespaced ids). */
export const SURF_MAP_REGISTRY: readonly RegistryEntry[] = OFFICIAL_SURF_MAP_REGISTRY;

export function getSurfRegistryEntry(trackId: string): RegistryEntry | undefined {
  return SURF_MAP_REGISTRY.find((e) => e.trackId === trackId);
}

/** Serialisable server copy of the SURF registry. */
export function getSurfAcceptedFingerprints(): Array<{
  trackId: string;
  mapVersion: number;
  mapFingerprint: string;
  movementVersion: string;
}> {
  return SURF_MAP_REGISTRY.map((e) => ({
    trackId: e.trackId,
    mapVersion: e.mapVersion,
    mapFingerprint: e.mapFingerprint,
    movementVersion: e.movementVersion
  }));
}

/** Debug helper: the identity string used to fingerprint a surf map. */
export function surfIdentityDebugString(track: GeneratedTrack, analysis: TrackAnalysis): string {
  return buildMapIdentityString(track, analysis);
}

/** Analysis fingerprint for an official surf preset (deterministic input check). */
export function surfAnalysisFingerprint(analysis: TrackAnalysis): string {
  return computeAnalysisIdentity(analysis).analysisFingerprint;
}
